var searchData=
[
  ['centralrolenotsupportedexception_0',['CentralRoleNotSupportedException',['../class_cosmed_ble_lib_1_1_central_role_not_supported_exception.html',1,'CosmedBleLib']]],
  ['characteristicreader_1',['CharacteristicReader',['../class_cosmed_ble_lib_1_1_characteristic_reader.html',1,'CosmedBleLib']]],
  ['clearadvertisementfilter_2',['ClearAdvertisementFilter',['../class_cosmed_ble_lib_1_1_filter_builder.html#afea94676e3ebdc3e26f5b36223554f14',1,'CosmedBleLib.FilterBuilder.ClearAdvertisementFilter()'],['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_advertisement_filter.html#ac8fe4ab2c2abf3b97bedd7ee7775c7be',1,'CosmedBleLib.CosmedBluetoothLEAdvertisementFilter.ClearAdvertisementFilter()']]],
  ['clearsignalstrengthfilter_3',['ClearSignalStrengthFilter',['../class_cosmed_ble_lib_1_1_filter_builder.html#a7c1c85136547c111c0cbe39db5e25784',1,'CosmedBleLib.FilterBuilder.ClearSignalStrengthFilter()'],['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_advertisement_filter.html#afc8dec283fee346e92e506b6236900e7',1,'CosmedBleLib.CosmedBluetoothLEAdvertisementFilter.ClearSignalStrengthFilter()']]],
  ['convertgattcharacteristicvaluetostring_4',['ConvertGattCharacteristicValueToString',['../class_cosmed_ble_lib_1_1_value_converter.html#afd698b407237771ebca97427b5d902f3',1,'CosmedBleLib::ValueConverter']]],
  ['convertvaluebuffertostring_5',['ConvertValueBufferToString',['../class_cosmed_ble_lib_1_1_value_converter.html#a99aeed8876de64284904687a677c3bdd',1,'CosmedBleLib::ValueConverter']]],
  ['cosmedbleadvertiseddevice_6',['CosmedBleAdvertisedDevice',['../class_cosmed_ble_lib_1_1_cosmed_ble_advertised_device.html#a0be9146029809c40ca3a9a3c436f6744',1,'CosmedBleLib.CosmedBleAdvertisedDevice.CosmedBleAdvertisedDevice()'],['../class_cosmed_ble_lib_1_1_cosmed_ble_advertised_device.html#a25af8f6bc848c962fe4b7a1cdf364496',1,'CosmedBleLib.CosmedBleAdvertisedDevice.CosmedBleAdvertisedDevice(ulong address, DateTimeOffset timestamp, bool isConnectable, BluetoothLEAdvertisement adv, BluetoothLEAdvertisementType advType)'],['../class_cosmed_ble_lib_1_1_cosmed_ble_advertised_device.html#a18f5e55883215b16f75681a299270cbd',1,'CosmedBleLib.CosmedBleAdvertisedDevice.CosmedBleAdvertisedDevice(BluetoothLEAdvertisementReceivedEventArgs args)'],['../class_cosmed_ble_lib_1_1_cosmed_ble_advertised_device.html',1,'CosmedBleLib.CosmedBleAdvertisedDevice']]],
  ['cosmedbledevice_7',['CosmedBleDevice',['../class_cosmed_ble_lib_1_1_cosmed_ble_device.html',1,'CosmedBleLib']]],
  ['cosmedblelib_8',['CosmedBleLib',['../namespace_cosmed_ble_lib.html',1,'']]],
  ['cosmedbluetoothleadapter_9',['CosmedBluetoothLEAdapter',['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_adapter.html',1,'CosmedBleLib']]],
  ['cosmedbluetoothleadvertisementfilter_10',['CosmedBluetoothLEAdvertisementFilter',['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_advertisement_filter.html',1,'CosmedBleLib.CosmedBluetoothLEAdvertisementFilter'],['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_advertisement_filter.html#ac9b90e4f0c37d1d722bbeb041f208c52',1,'CosmedBleLib.CosmedBluetoothLEAdvertisementFilter.CosmedBluetoothLEAdvertisementFilter()']]],
  ['cosmedbluetoothleadvertisementwatcher_11',['CosmedBluetoothLEAdvertisementWatcher',['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_advertisement_watcher.html',1,'CosmedBleLib.CosmedBluetoothLEAdvertisementWatcher'],['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_advertisement_watcher.html#ae33e6b7d871a949dd9eda9bc82449199',1,'CosmedBleLib.CosmedBluetoothLEAdvertisementWatcher.CosmedBluetoothLEAdvertisementWatcher()'],['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_advertisement_watcher.html#aed0e4c204be66f8f781213c95ee28919',1,'CosmedBleLib.CosmedBluetoothLEAdvertisementWatcher.CosmedBluetoothLEAdvertisementWatcher(IFilter filter)']]],
  ['cosmedcharacteristicreadresult_12',['CosmedCharacteristicReadResult',['../class_cosmed_ble_lib_1_1_cosmed_characteristic_read_result.html',1,'CosmedBleLib']]],
  ['cosmedcharacteristicsubscriptionresult_13',['CosmedCharacteristicSubscriptionResult',['../class_cosmed_ble_lib_1_1_cosmed_characteristic_subscription_result.html',1,'CosmedBleLib']]],
  ['cosmedcharacteristicwriteresult_14',['CosmedCharacteristicWriteResult',['../class_cosmed_ble_lib_1_1_cosmed_characteristic_write_result.html',1,'CosmedBleLib']]],
  ['cosmedgattcharacteristic_15',['CosmedGattCharacteristic',['../class_cosmed_ble_lib_1_1_cosmed_gatt_characteristic.html',1,'CosmedBleLib']]],
  ['cosmedgatterrorfoundeventargs_16',['CosmedGattErrorFoundEventArgs',['../class_cosmed_ble_lib_1_1_cosmed_gatt_error_found_event_args.html',1,'CosmedBleLib']]],
  ['createasync_17',['CreateAsync',['../class_cosmed_ble_lib_1_1_cosmed_bluetooth_l_e_adapter.html#aea8128d36bda9352eb82d119c0268cd1',1,'CosmedBleLib::CosmedBluetoothLEAdapter']]]
];
